# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5654c236fa0b17db8e0a0b4096538b4b32fa1827a4911834c4fb59dce60be2d1e8d295b85289a511240db055a8b5e68429248bb69887a8dbf2631844adfc9fc5
  recaptcha_key: 6LcoUR4UAAAAADkmyplKx1WCCuxFHvGgtwOxNq80

test:
  secret_key_base: 8846ba3620c61241f9c39078f49a181449c8addfd6fd75ea4b4415a73e49c04f4e2da44de3b61fff3c8edb05a37c846c879913cebda3f92a6df201a20becd266

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
